# numpy 数组规整

亦即重塑数组的维度 & 形状
◄ numpy.append() 用于将值添加到数组的末尾，生成一个新的数组，并不会修改原始数组
◄ numpy.arange() 创建一个具有指定范围、间隔和数据类型的等间隔数组
◄ numpy.block() 用于按照指定的块结构组合多个数组，生成一个新的数组
◄ numpy.column_stack() 按列堆叠多个数组，生成一个新的二维数组
◄ numpy.concatenate() 沿指定轴连接多个数组，生成一个新的数组
◄ numpy.delete() 用于删除数组中指定位置的元素，生成一个新的数组，并不会修改原始数组
◄ numpy.flatten() 用于将多维数组转换为一维数组。与 numpy.ravel() 不同的是，numpy.flatten() 返回数组的副本，而不是原始数组的视图
◄ numpy.flip() 用于沿指定轴翻转数组的元素顺序
◄ numpy.fliplr() 沿着水平方向 (左右方向) 翻转数组的元素顺序
◄ numpy.flipud() 沿着垂直方向 (上下方向) 翻转数组的元素顺序
◄ numpy.hsplit() 用于沿水平方向分割数组为多个子数组
◄ numpy.hstack() 按水平方向堆叠多个数组，生成一个新的数组
◄ numpy.insert() 用于在数组的指定位置插入值，生成一个新的数组，并不会修改原始数组
◄ numpy.ravel() 用于将多维数组转换为一维数组，按照 C 风格的顺序展平数组元素
◄ numpy.repeat() 将数组中的元素重复指定次数，生成一个新的数组
◄ numpy.reshape() 用于改变数组的形状，重新排列数组元素，但不改变原始数据本身
◄ numpy.resize() 用于调整数组的形状，并可以在必要时重复数组的元素来填充新的形状
◄ numpy.rot90() 默认将数组按指定次数逆时针旋转 90 度
◄ numpy.row_stack() 按行堆叠多个数组，生成一个新的数组
◄ numpy.shares_memory() 用于检查两个数组是否共享相同的内存位置
◄ numpy.split() 用于将数组沿指定轴进行分割成多个子数组
◄ numpy.squeeze() 用于从数组的形状中去除维度为1 的维度，使得数组更紧凑
◄ numpy.stack() 用于沿新的轴将多个数组堆叠在一起，生成一个新的数组
◄ numpy.swapaxes() 用于交换数组的两个指定轴的位置
◄ numpy.tile() 用于将数组沿指定方向重复指定次数，生成一个新的数组
◄ numpy.transpose() 完成矩阵转置，即将数组的行和列进行互换
◄ numpy.vsplit() 用于沿垂直方向分割数组为多个子数组
◄ numpy.vstack() 按垂直方向堆叠多个数组，生成一个新的数组

## reshape 函数

numpy.reshape(a, newshape, order='C')

这个函数的重要输入参数：
* a 参数是要被重塑的数组，可以是一个数组对象，也可以是一个 Python 列表、元组等支持迭代的对象。
* newshape 参数是新的形状，可以是一个整数元组或列表，也可以是一个整数序列。
* order 参数表示重塑数组的元素在内存中存储的顺序，可以是 'C' (按行顺序存储) 或 'F' (按列顺序存储)，默认值为'C'。 (即新形状的数据是怎么在内存中存储的)

**如果改变后的形状与原数组的数量不一致,将会抛出 ValueError Exception**
**注意，使用 -1 作为形状参数时，numpy.reshape() 会根据数组中的数据数量和其它指定的维数来自动计算该维度的大小。**

In [4]:
import numpy as np
num = np.arange(-7,8)
num_1 = num.reshape(3,5,order='C')
num_2 = num.reshape(3,5,order='F')
print("num_1", num_1)
print("num_2", num_2)
print('num_3', num.reshape(5,-1))  # -1:自動計算,由于行数已知为 5,所以计算列数为 3; 因此,如果行数设置为 1,则列数为 15,变成了行向量
print('num_4', num.reshape(1,-1), num.reshape(1,-1).shape)  # -1:自動計算,由于行数已知为 1,所以计算列数为 15,变成了行向量

num_1 [[-7 -6 -5 -4 -3]
 [-2 -1  0  1  2]
 [ 3  4  5  6  7]]
num_2 [[-7 -4 -1  2  5]
 [-6 -3  0  3  6]
 [-5 -2  1  4  7]]
num_3 [[-7 -6 -5]
 [-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
num_4 [[-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7]] (1, 15)


## 视图 vs 副本

牢记判断两个 array 是否指向同一个内存的办法:`numpy.shares_memory(a1,a2)`

## 数组转置操作

两种方法:
1. numpy.transpose()
2. .T 属性

二者都是返回原始数组的转置,并且是视图,而非副本

**一维数组转置不会产生变化**

In [6]:
a = np.arange(1, 10)
print('a', a)
print('a.T', a.T)

a [1 2 3 4 5 6 7 8 9]
a.T [1 2 3 4 5 6 7 8 9]


## 扁平化

多种方法:
1. array.ravel() # 返回的是副本
2. array.reshape(-1)
3. array.flatten()

后两个都是视图

## 旋转&反转

1. numpy.rot90()  # 将一个数组逆时针旋转 90 度
2. numpy.flip()   # 反转数组中的元素,将数组沿着一个或多个轴翻转 

> numpy.flip(A,axis=None) 中，A 是要进行翻转的数组，axis 指定要翻转的轴。
> 如图 12 所示，如果不指定 axis，则默认将整个数组沿着所有的轴进行翻转。

## 堆叠

1. numpy.stack() # 沿着指定轴将多个数组堆叠在一起,返回一个新数组,默认轴为 axis = 0
2. numpy.row_stack() # 将多个数组沿着行方向进行堆叠, 生成一个新的数组.
3. numpy.vstack()  # 将多个数组沿着垂直方向(行方向)进行堆叠, 生成一个新的数组

1. numpy.concatenate()  # 拼接

In [8]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)
print("numpy.stack((a1,a2))\n", np.stack((a1,a2)))
print("numpy.row_stack((a1,a2))\n", np.row_stack((a1,a2)))
print("numpy.column_stack((a1,a2))\n", np.column_stack((a1,a2)))
print("numpy.hstack((a1,a2))\n", np.hstack((a1,a2)))  # 注意这个和 column_stack 的区别,要获得正确的结果,a1 和 a2 必须是列向量
print("numpy.vstack((a1,a2))\n", np.vstack((a1,a2)))

numpy.stack((a1,a2))
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
numpy.row_stack((a1,a2))
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
numpy.column_stack((a1,a2))
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
numpy.hstack((a1,a2))
 [ 1  2  3  4  5  6  7  8  9 10]
numpy.vstack((a1,a2))
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# 拼接
a = np.arange(1, 10).reshape(3,3)
b = np.arange(11, 20).reshape(3,3)
print('a\n', a)
print('b\n', b)
print('np.concatenate((a,b))\n', np.concatenate((a,b)))
print('np.concatenate((a,b), axis=0)\n', np.concatenate((a,b), axis=0))
print('np.concatenate((a,b), axis=1)\n', np.concatenate((a,b), axis=1))

a
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
np.concatenate((a,b))
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
np.concatenate((a,b), axis=0)
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
np.concatenate((a,b), axis=1)
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


## 重复

1. numpy.repeat()
2. numpy.tile()

numpy.repeat() 和numpy.tile() 的区别在于重复的对象不同。numpy.repeat() 重复的是分别数组中的每个元素。numpy.repeat() 还可以指定具体
的轴，以及不同元素重复的次

In [11]:
# test np.repeat() np.tile()
a = np.arange(1, 5)
print('a', a)
print('np.repeat(a, 2)', np.repeat(a, 2))
print('np.tile(a, 2)', np.tile(a, 2))


a [1 2 3 4]
np.repeat(a, 2) [1 1 2 2 3 3 4 4]
np.tile(a, 2) [1 2 3 4 1 2 3 4]


## 分块矩阵

### 组合
numpy.block() 函数用于将多个数组沿不同的轴组合成一个分块矩阵。它接受一个嵌套列表作为输入，每个列表代表一个块矩阵，然后根据指定的轴将这些块矩阵组合在一起。

### 切割
沿指定轴numpy.split()  # 一维数组切成几等份,二维数组默认沿着 aixs = 0 均切.
                      # 注意,默认均等切的话,要保证可均分


In [12]:
A = np.eye(2)
B = np.arange(-4,4+1).reshape(3,3)
M = np.block([[A,                np.zeros((2, 3))],
              [np.zeros((3, 2)), B               ]])  # 里面是一个嵌套列表,只要里面的 array 的维度相同,就可以拼接
M

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0., -4., -3., -2.],
       [ 0.,  0., -1.,  0.,  1.],
       [ 0.,  0.,  2.,  3.,  4.]])

In [17]:
a_1D = np.arange(-9,9)
print('a_1D\n', a_1D)
a_3_splits = np.split(a_1D, 3)
print('a_3_splits\n', a_3_splits)
print('a_3_splits[0]\n', a_3_splits[0])

print("split at specified positions")
a_3_splits = np.split(a_1D, [2, 5, 7])
print('a_3_splits with [2,5,7]\n', a_3_splits)

a_1D
 [-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8]
a_3_splits
 [array([-9, -8, -7, -6, -5, -4]), array([-3, -2, -1,  0,  1,  2]), array([3, 4, 5, 6, 7, 8])]
a_3_splits[0]
 [-9 -8 -7 -6 -5 -4]
split at specified positions
a_3_splits with [2,5,7]
 [array([-9, -8]), array([-7, -6, -5]), array([-4, -3]), array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])]


In [18]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## append insert delete

当涉及到NumPy库的delete、append和insert函数时，它们都是用于在数组中进行元素的删除、添加和插入操作的函数。

np.delete(arr, obj, axis=None)：
arr：要删除元素的数组。
obj：指定要删除的元素的索引或切片。
axis：可选参数，用于指定沿着哪个轴删除元素。默认为None，表示在扁平化的数组上进行删除。
np.delete()函数可以用于从数组中删除指定索引或切片的元素，并返回一个新的数组。删除操作不会更改原始数组。

以下是示例用法：

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr = np.delete(arr, 2)  # 删除索引为2的元素

print("Original Array:", arr)
print("New Array:", new_arr)
```
在这个示例中，我们创建了一个包含整数的数组arr。然后，我们使用np.delete()函数删除了索引为2的元素，返回了一个新的数组new_arr。

np.append(arr, values, axis=None)：
arr：要添加元素的数组。
values：要添加到数组的值，可以是一个数值或一个数组。
axis：可选参数，用于指定沿着哪个轴添加元素。默认为None，表示将数组扁平化后添加元素。
np.append()函数可以用于在数组的末尾添加一个或多个元素，并返回一个新的数组。添加操作不会更改原始数组。

以下是示例用法：

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr = np.append(arr, 6)  # 在末尾添加元素6

print("Original Array:", arr)
print("New Array:", new_arr)
```
在这个示例中，我们创建了一个包含整数的数组arr。然后，我们使用np.append()函数在数组末尾添加了元素6，返回了一个新的数组new_arr。

np.insert(arr, obj, values, axis=None)：
arr：要插入元素的数组。
obj：指定要插入元素的索引位置。
values：要插入的值，可以是一个数值或一个数组。
axis：可选参数，用于指定沿着哪个轴插入元素。默认为None，表示将数组扁平化后插入元素。
np.insert()函数可以用于在数组的指定位置插入一个或多个元素，并返回一个新的数组。插入操作不会更改原始数组。

以下是示例用法：

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, [6, 7])  # 在索引2处插入元素6和7

print("Original Array:", arr)
print("New Array:", new_arr)
```
在这个示例中，我们创建了一个包含整数的数组arr。然后，我们使用np.insert()函数在索引2处插入了元素6和7，返回了一个新的数组new_arr。

需要注意的是，delete、append和insert函数都返回新的数组，并不会修改原始数组。如果你想在原始数组上进行修改，需要将返回的新数组赋值给原始数组。